version: 0.2

env:
  variables:
    dockerhub_user: "adam9098"
    cdk_version: "v1.10.0"
  parameter-store:
    dockerhub_password: '/prod/dockerhub-password'

phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - docker login -u $dockerhub_user -p $dockerhub_password
  build:
    commands:
      - tags="-t adam9098/aws-cdk:"$cdk_version" -t adam9098/aws-cdk:latest"
      - cdk_version_clean=$(echo $cdk_version|sed 's/v//')
      - sed -i "s|{{CDK_VERSION}}|$cdk_version_clean|g" Dockerfile requirements.txt
      - docker build --no-cache $tags .
  post_build:
    commands:
      - docker push adam9098/aws-cdk:"$cdk_version"
      - docker push adam9098/aws-cdk:latest

